# Generated by Django 3.1.4 on 2020-12-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30, null=True)),
                ('formatted_address', models.CharField(max_length=100, null=True)),
                ('business_status', models.CharField(max_length=30, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('user_ratings_total', models.IntegerField(null=True)),
                ('utc_offset', models.IntegerField(null=True)),
            ],
        ),
    ]
